// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWcTMYD2o9jOtBt9cs0E9EgAEvh_w6-A',
    appId: '1:667433369105:web:e140f4233c4993bff73bb0',
    messagingSenderId: '667433369105',
    projectId: 'hoctaponluyen',
    authDomain: 'hoctaponluyen.firebaseapp.com',
    storageBucket: 'hoctaponluyen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_-s_SdBAQmAx3Tvcbi9gKQObEaOAoU4',
    appId: '1:667433369105:android:ffe198621271b20df73bb0',
    messagingSenderId: '667433369105',
    projectId: 'hoctaponluyen',
    storageBucket: 'hoctaponluyen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47EKl1xgsKLSYSHeDus2AgJLSDvvBADQ',
    appId: '1:667433369105:ios:f2bde57483dce621f73bb0',
    messagingSenderId: '667433369105',
    projectId: 'hoctaponluyen',
    storageBucket: 'hoctaponluyen.firebasestorage.app',
    iosBundleId: 'com.example.hocTapOnLuyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47EKl1xgsKLSYSHeDus2AgJLSDvvBADQ',
    appId: '1:667433369105:ios:f2bde57483dce621f73bb0',
    messagingSenderId: '667433369105',
    projectId: 'hoctaponluyen',
    storageBucket: 'hoctaponluyen.firebasestorage.app',
    iosBundleId: 'com.example.hocTapOnLuyen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQWcTMYD2o9jOtBt9cs0E9EgAEvh_w6-A',
    appId: '1:667433369105:web:68d287f957d3159bf73bb0',
    messagingSenderId: '667433369105',
    projectId: 'hoctaponluyen',
    authDomain: 'hoctaponluyen.firebaseapp.com',
    storageBucket: 'hoctaponluyen.firebasestorage.app',
  );
}
